

on: [push, pull_request]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install shiny
        run: |
          install.packages(c("shiny", "rsconnect"), type = "binary")
        shell: Rscript {0}
      - name: authorise-shiny
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN}}
          SHINYAPPS_SECRET: ${{ secrets.SHINAPPYS_SECRET}}
        run: Rscript -e 'args <- commandArgs(trailingOnly = TRUE)' -e 'rsconnect::setAccountInfo(name = "mattcowgill", token = args[1], secret = args[2])' "$SHINYAPPS_TOKEN" "$SHINYAPPS_SECRET"
      - name: deploy-app
        run: Rscript -e 'rsconnect::deployApp()'
